// Mock data for development without database

export const mockUsers = [
  {
    _id: 'user1',
    username: 'ProGamer99',
    email: 'progamer@test.com',
    gamerTag: 'ProGamer#1234',
    avatar: '',
    bio: 'Professional esports player',
    favoriteGames: ['Valorant', 'CS2'],
    followers: [],
    following: [],
    isVerified: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user2',
    username: 'NightHawk',
    email: 'nighthawk@test.com',
    gamerTag: 'NightHawk#5678',
    avatar: '',
    bio: 'Casual gamer and streamer',
    favoriteGames: ['League of Legends', 'Valorant'],
    followers: [],
    following: [],
    isVerified: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'user3',
    username: 'ShadowKing',
    email: 'shadow@test.com',
    gamerTag: 'ShadowKing#9999',
    avatar: '',
    bio: 'Gaming enthusiast',
    favoriteGames: ['Fortnite', 'Apex Legends'],
    followers: [],
    following: [],
    isVerified: false,
    createdAt: new Date().toISOString(),
  },
];

export const mockPosts = [
  {
    _id: 'post1',
    author: {
      _id: 'user1',
      username: 'ProGamer99',
      gamerTag: 'ProGamer#1234',
      avatar: '',
    },
    content: '🎮 Just hit Immortal in Valorant! The grind was real but totally worth it. Who else is grinding ranked this season?',
    images: [],
    reactions: [
      { user: 'user2', type: 'fire' },
      { user: 'user3', type: 'like' },
    ],
    comments: [
      {
        _id: 'comment1',
        user: { _id: 'user2', username: 'NightHawk', avatar: '' },
        content: 'Congrats! That\'s insane! 🔥',
        createdAt: new Date(Date.now() - 3600000).toISOString(),
      },
    ],
    gameTag: 'Valorant',
    viewCount: 156,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    isEdited: false,
    visibility: 'public',
  },
  {
    _id: 'post2',
    author: {
      _id: 'user2',
      username: 'NightHawk',
      gamerTag: 'NightHawk#5678',
      avatar: '',
    },
    content: 'Looking for a squad to play CS2 tonight! Must have mic and good vibes. Drop your Steam ID below 👇',
    images: [],
    reactions: [
      { user: 'user1', type: 'like' },
    ],
    comments: [],
    gameTag: 'Counter-Strike 2',
    viewCount: 89,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    isEdited: false,
    visibility: 'public',
  },
  {
    _id: 'post3',
    author: {
      _id: 'user3',
      username: 'ShadowKing',
      gamerTag: 'ShadowKing#9999',
      avatar: '',
    },
    content: 'The new Fortnite season is actually amazing! The new map changes and weapons are so fun. What do you all think? 🏝️',
    images: [],
    reactions: [
      { user: 'user1', type: 'love' },
      { user: 'user2', type: 'like' },
    ],
    comments: [
      {
        _id: 'comment2',
        user: { _id: 'user1', username: 'ProGamer99', avatar: '' },
        content: 'The mobility items are crazy this season!',
        createdAt: new Date(Date.now() - 1800000).toISOString(),
      },
    ],
    gameTag: 'Fortnite',
    viewCount: 234,
    createdAt: new Date(Date.now() - 28800000).toISOString(),
    isEdited: false,
    visibility: 'public',
  },
  {
    _id: 'post4',
    author: {
      _id: 'user1',
      username: 'ProGamer99',
      gamerTag: 'ProGamer#1234',
      avatar: '',
    },
    content: 'Tournament practice going well! Our team is looking solid for the upcoming qualifiers. Stay tuned for updates! 💪🏆',
    images: [],
    reactions: [
      { user: 'user2', type: 'fire' },
      { user: 'user3', type: 'fire' },
    ],
    comments: [],
    gameTag: 'Valorant',
    viewCount: 312,
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    isEdited: false,
    visibility: 'public',
  },
];

export const mockVideos = [
  {
    _id: 'video1',
    author: { _id: 'user1', username: 'ProGamer99', avatar: '' },
    title: 'Insane Valorant Ace - 1v5 Clutch',
    description: 'Watch me clutch this impossible round!',
    thumbnailUrl: '',
    videoUrl: '',
    duration: 120,
    viewCount: 1520,
    reactions: [],
    gameTag: 'Valorant',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'video2',
    author: { _id: 'user2', username: 'NightHawk', avatar: '' },
    title: 'CS2 Tips for Beginners',
    description: 'Essential tips to improve your game',
    thumbnailUrl: '',
    videoUrl: '',
    duration: 540,
    viewCount: 3200,
    reactions: [],
    gameTag: 'Counter-Strike 2',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const mockLiveStreams: any[] = [];

export const mockAnonymousPosts = [
  {
    _id: 'anon1',
    anonymousId: 'Shadow_User_7829',
    content: 'Anyone else feel like matchmaking is rigged sometimes? I swear I only get paired with new players in ranked 😅',
    community: 'gaming-confessions',
    reactions: [{ type: 'like', count: 12 }, { type: 'fire', count: 3 }],
    comments: [],
    viewCount: 89,
    isHidden: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    _id: 'anon2',
    anonymousId: 'Ghost_Gamer_1234',
    content: 'Unpopular opinion: Mobile gaming is just as valid as PC/console gaming. Fight me.',
    community: 'hot-takes',
    reactions: [{ type: 'like', count: 45 }, { type: 'fire', count: 28 }],
    comments: [],
    viewCount: 234,
    isHidden: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    _id: 'anon3',
    anonymousId: 'Ninja_Player_5678',
    content: 'I\'ve been gaming for 10 years and still get nervous before ranked matches. Is that normal?',
    community: 'gaming-confessions',
    reactions: [{ type: 'love', count: 67 }, { type: 'like', count: 34 }],
    comments: [],
    viewCount: 456,
    isHidden: false,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
];

export const mockGameHubs = [
  {
    _id: 'game1',
    name: 'Valorant',
    slug: 'valorant',
    description: 'Tactical shooter by Riot Games',
    coverImage: '',
    icon: '',
    memberCount: 15420,
    postCount: 8930,
    category: 'FPS',
  },
  {
    _id: 'game2',
    name: 'League of Legends',
    slug: 'league-of-legends',
    description: 'MOBA by Riot Games',
    coverImage: '',
    icon: '',
    memberCount: 28500,
    postCount: 15200,
    category: 'MOBA',
  },
  {
    _id: 'game3',
    name: 'Counter-Strike 2',
    slug: 'cs2',
    description: 'Competitive FPS by Valve',
    coverImage: '',
    icon: '',
    memberCount: 12300,
    postCount: 6700,
    category: 'FPS',
  },
];

// Demo user for login (password: demo123)
export const demoUser = {
  _id: 'demo-user',
  username: 'DemoUser',
  email: 'demo@nexo.com',
  gamerTag: 'DemoUser#0001',
  avatar: '',
  bio: 'Testing NEXO Gaming Platform',
  favoriteGames: ['Valorant', 'Fortnite'],
  followers: [],
  following: [],
  isVerified: false,
  createdAt: new Date().toISOString(),
};
